version: '3'
services:
    crowdsec:
        image: crowdsecurity/crowdsec:v1.0.0
        environment:
        - DISABLE_AGENT=true
    web:
        # wp-admin/admin.php?page=crowdsec_plugin
        image: wordpress:5.6-php7.2
        links:
        - mysql
        environment:
        - WORDPRESS_DB_PASSWORD=super_secret_password
        - WORDPRESS_DEBUG=1
        # more here https://hub.docker.com/_/wordpress
        ports:
        - "8081:80"
        volumes:
        - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer

        # Optional (only if your want to make changes to library source code in the same time)
        # Set the absolute path to the source of the library below to both sides of the volume.
        # This technique is required when symlinking in docker containers, as mentionned here.
        # https://stackoverflow.com/questions/38485607/mount-host-directory-with-a-symbolic-link-inside-in-docker-container/40322275#40322275
        
        #- <absolute_path_to_the_source_code_of_the_php_bouncer_lib>:<absolute_path_to_the_source_code_of_the_php_bouncer_lib>
    mysql:
        image: mysql:5.7
        environment:
        - MYSQL_ROOT_PASSWORD=super_secret_password
        - MYSQL_DATABASE=wordpress