version: "3"
services:
    web:
        build:
            context: .
            dockerfile: ./docker/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        links:
            - crowdsec
            - mysql
            - redis
            - memcached

        environment:
            - WORDPRESS_DB_PASSWORD=super_secret_password
            - WORDPRESS_DEBUG=1
            #- WORDPRESS_CONFIG_EXTRA=define('DISABLE_WP_CRON', true);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer
    crowdsec:
        image: crowdsecurity/crowdsec:latest
        environment:
            - DISABLE_AGENT=true
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=super_secret_password
            - MYSQL_DATABASE=wordpress
    redis:
        image: redis:6-alpine
        ports:
            - "6379:6379"
    memcached:
        image: memcached:1-alpine
