version: "3"
services:
    wordpress5-7:
        build:
            context: .
            dockerfile: ./docker/wp5.7/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_USER: root
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw
    wordpress5-6:
        build:
            context: .
            dockerfile: ./docker/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    wordpress5-5:
        build:
            context: .
            dockerfile: ./docker/wp5.5/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    wordpress5-4:
        build:
            context: .
            dockerfile: ./docker/wp5.4/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    wordpress5-3:
        build:
            context: .
            dockerfile: ./docker/wp5.3/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    wordpress5-2:
        build:
            context: .
            dockerfile: ./docker/wp5.2/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    wordpress5-1:
        build:
            context: .
            dockerfile: ./docker/wp5.1/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw

    wordpress5-0:
        build:
            context: .
            dockerfile: ./docker/wp5.0/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    wordpress4-9:
        build:
            context: .
            dockerfile: ./docker/wp4.9/php-${CS_WORDPRESS_BOUNCER_PHP_VERSION}.Dockerfile
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        environment:
            WORDPRESS_DB_PASSWORD: super_secret_password
            WORDPRESS_DEBUG: 1 # Comment this line the simulate the production mode
            WORDPRESS_CONFIG_EXTRA: |
                define('WP_CRON_LOCK_TIMEOUT', 1);
        # more here https://hub.docker.com/_/wordpress
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/wp-content/plugins/cs-wordpress-bouncer:rw
            - ./docker/tests.htaccess:/var/www/html/.htaccess:rw

    crowdsec:
        image: crowdsecurity/crowdsec:latest
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        environment:
            - DISABLE_AGENT=true
        ports:
            - "8051:8080"
    mysql:
        image: mysql:5.7
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        environment:
            - MYSQL_ROOT_PASSWORD=super_secret_password
            - MYSQL_DATABASE=wordpress
    redis:
        image: redis:6-alpine
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
    memcached:
        image: memcached:1-alpine
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
    wpscan:
        image: wpscanteam/wpscan
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
    e2e:
        image: mcr.microsoft.com/playwright:focal
        networks:
            - wordpress_bouncer_network_ipv4
            #- wordpress_bouncer_network_ipv6
        environment:
            LAPI_URL_FROM_WP: http://crowdsec:8080
            LAPI_URL_FROM_E2E: http://crowdsec:8080
            NETWORK_IFACE: eth0
            WORDPRESS_VERSION: ${WORDPRESS_VERSION}
            WATCHER_LOGIN: ${WATCHER_LOGIN}
            WATCHER_PASSWORD: ${WATCHER_PASSWORD}
            BOUNCER_KEY: ${BOUNCER_KEY}
            WORDPRESS_URL: ${WORDPRESS_URL}
        depends_on:
            - crowdsec
            - mysql
            - redis
            - memcached
        volumes:
            - ./tests/e2e:/var/run/tests:rw
        command: tail -F anything

networks:
    wordpress_bouncer_network_ipv4:
        name: wordpress_bouncer_network_ipv4
        #enable_ipv6: false
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
    # wordpress_bouncer_network_ipv6:
    #     name: wordpress_bouncer_network
    #     enable_ipv6: true
    #     ipam:
    #         config:
    #             - subnet: 2001:3200:3200::/64
    #               gateway: 2001:3200:3200::1
